version: "3" ## especifica a versão do docker-compose file

services:
  ## Define um serviço
  mongo_db_judge:
   image: mongo
   container_name: mongo_db_judge_container
   volumes:
     - ~/Documentos/docker/mongo:/data/db
   ports:
     - 27017:27017
   environment:
     - MONGO_INITDB_ROOT_USERNAME=yure
     - MONGO_INITDB_ROOT_PASSWORD=mongo123
  judge:
    ## nome do serviço
    image: judge_image
    container_name: judge_container
    depends_on:
      - mongo_db_judge
    build: .
    ports:
      - ${PORT}:${PORT} ## redirecionamento de porta quando chegar alguma requisição na porta 3000 chama o container na porta 3000
    env_file:
      - .env

